name: CI

on:
  pull_request:
  push:
    # branches:
    #   - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.11
              otp: 23.3
            lint: lint
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1.7
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - run: mix deps.get

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - uses: actions/cache@v2
        with:
          path: ~/tmp
          key: tmp4-${{ hashFiles('~/tmp/*') }}
          restore-keys: tmp4-

      - run: echo ~/tmp/*

      - run: echo "${{ hashFiles('tmp/*') }}"

      - run: mkdir -p ~/tmp

      - run: ls -la ~/tmp

      - run: mix test
        env:
          TMPDIR: ~/tmp
